name: weather
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  sqflite:
  path_provider:
  flutter_bloc: ^8.0.1
  flare_flutter:
  # flare_ flutter это старый пакет. Новое название сервиса это Rive, у меня просто была хорошая аннимация нарисованная как раз таки еще давно на flare, поэтому и использовал ее
  flutter_spinkit: ^5.1.0
  another_flushbar: ^1.10.29
  intl: ^0.17.0
  fl_chart: ^0.55.1
  get_it: ^7.2.0
  loader_overlay: ^2.0.5+1
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  #flutter pub run flutter_launcher_icons:main

flutter_icons:
  image_path_android: 'assets/ico_android.png'
  image_path_ios: 'assets/ico_ios.png'
  android: true
  ios: true


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/weather/
    - assets/flare/
    - assets/details/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
